//
//  ConversationTopicDataBase.swift
//  AIChatBot
//
//  Created by TEAGAN RETT on 1/10/22.
//

import Foundation

import Foundation
public class ConversationTopicDataBase{
    
    //sports
    var sports = ["PLAY", "BASKETBALL", "BASEBALL", "VOLLEYBALL", "HOCKEY", "FOOTBALL", "SOCCER", "SWIMMING", "SWIM", "RUNNING", "TRACK", "DEFENSE", "OFFENSE", "WIN", "LOSE", "TOURNAMENT", "BALL"]
    
    var basketball = ["BASKETBALL", "COURT", "ORANGE", "B-BALL", "GUARD", "FORWARD", "SHOOTING", "NET", "SLAM DUNK", "HOOP", "BACKBOARD", "DRIBBLE", "NBA", "WNBA", "BULLS", "LAKERS", "WARRIORS", "NETS", "SUNS", "RAPTORS", "CELTICS", "KNICKS", "HEAT", "MAVERICKS", "BUCKS", "CAVALIERS", "JAZZ", "76ERS", "SPURS", "CLIPPERS", "NUGGETS", "GRIZZLIES", "HORNETS", "WIZARDS", "ROCKETS", "BLAZERS", "KINGS", "TIMBERWOLVES", "PACERS", "HAWKS", "PELICANS", "PISTONS", "CITY THUNDER", "MAGIC", "MYSTICS", "SKY", "ACES", "STORM", "LYNX", "LIBERTY", "MERCURY", "SPARKS", "DREAM", "WINGS", "FEVER", "COMETS", "STARS", "STING", "MONARCHS", "SHOCKS", "ROCKERS", "STARZZ", "SOL", "FIRE", "MIRACLE", "RAGE", "DEFENSE", "OFFENSE", "STEAL", "SHOT", "LAYUP"]
    
    var baseball = ["BASEBALL", "SOFTBALL", "BAT", "FEILD", "DIAMOND", "OUTFEILD", "INFEILD", "MOUND", "BASE", "PITCHER", "FIRSTBASE", "SECONDBASE", "THIRDBASE", "CATCHER", "SHORTSTOP", "RIGHT", "LEFT", "CENTER", "SINGLE", "HOMERUN", "BALL", "STRIKE", "UMPIRE", "MLB", "YANKEES", "BRAVES", "RED SOX", "ASTROS", "DODGERS", "RAYS", "GIANTS", "METS", "ANGELS", "CUBS", "GUARDIANS", "CARDINALS", "MARLINS", "ORIOLES", "ATHLETICS", "PHILLIES", "TIGERS", "WHITE SOX", "TWINS", "REDS", "BLUE JAYS", "RANGERS", "NATIONALS", "ROYALS", "BREWERS", "PIRATES"]
    
    var volleyball = ["VOLLEYBALL", "NET", "SPIKE", "SET", "PASS", "SERVE", "SETTER", "LIBERO", "BLOCKER", "HITTER", "HIT", "DIG", "BLOCK", "DS", "DEFENSE", "OFFENSE"]
    
    var hockey = ["HOCKEY", "PUCK", "ICE", "ICERINK", "RINK", "STICK", "HOCKEY STICK", "NHL", "HURRICANES", "BLUEJACKETS", "DEVILS", "ISLANDERS", "RANGERS", "FLYERS", "PENGUINS", "CAPITALS", "COYOTES", "BLACKHAWKS", "AVALANCHE", "STARS", "WILD", "PREDATORS", "BLUES", "JETS", "BRUINS", "SABERS", "RED WINGS", "PANTHERS", "CANADIENS", "SENATORS", "LIGHTING", "MAPLE LEAFS", "DUCKS", "FLAMES", "OILERS", "KINGS", "SHARKS", "SEATTLE KRAKEN", "CANUCKS", "GOLDEN KNIGHTS"]
    
    var football = ["FOOTBALL", "FEILD", "YARD LINE", "TACKLE", "TOUCHDOWN", "FEILD GOAL", "CENTER", "OFFENSIVE GUARD", "OFFENSIVE TACKLE", "QUARTERBACK", "RUNNING BACK", "WIDE REVEIVER", "TIGHT END", "DEFENSIVE TACKLE", "OFFENSE", "DEFFENSE", "NFL", "BUCCANEERS", "RAIDERS", "PACKERS", "EAGLES", "49ERS", "CHEIFS", "PATRIOTS", "COLTS", "RAVENS", "SAINTS", "RAMS", "VIKINGS", "BRONCOS", "DOLPHINS", "TITANS", "SEAHAWKS", "WASHINGTON FOOTBALL TEAM", "BEARS", "GIANTS", "LIONS", "JAGUARS", "PANTHERS", "JETS", "TEXANS", "COWBOYS", "STEELERS"]
    
    var soccer = ["SOCCER", "FEILD", "GOAL", "GOALIE BOX", "GOALIE", "GOALKEEPER", "DEFFENDER", "MIDDLE FEILDER", "FORWARD", "BALL", "WORLD CUP"]
    
    var swimming = ["SWIMMING", "SWIM", "POOL", "WATER", "SUIT", "SWIM SUIT", "GOGGLES", "DIVE", "DIVEING", "PHELPS", "FLOAT", "FRONT STROKE", "BACK STROKE", "BUTTERFLY STROKE", "BREAT STROKE", "WET", "LAP"]
    
    var running = ["RUNNING", "RUN", "TRACK", "SPRINT", "JOG", "CROSS COUNTRY", "FAST"]
    
    //school
    var school = ["SCHOOL", "HIGH", "FRESHMAN", "JUNIOR", "SENIOR", "GRADUATE", "TEACHER", "STUDENT", "HOMEWORK", "CLASS", "FRIENDS", "ASSIGNMENT", "ACADEMY", "HALL", "COLLEGE", "COURSE", "CLASSES", "COURSES", "EDUCATION", "GRADES", "TEST", "FINAL", "FINALS", "CAMPUS", "TEACHING", "STUDY", "ELEMENTRY", "MIDDLE", "COLLEGE", "TEXT BOOK"]
    
    var classes = ["COMPUTER SCIENCE", "MATH", "ENGLISH", "HISTORY", "SOCIAL STUDIES", "SCIENCE"]
    
    var computerScience = ["COMPUTER SCIENCE", "PROGRAM", "PROGRAMMING", "PROGRAMER", "CODE", "CODING", "JAVA", "SWIFT", "LANGUAGE", "SOFTWARE", "COMPUTER", "SEAVER", "XCODE", "BLUEJ", "JAVASCRIPT", "NETWORK", "LIT", "HACK"]
    
    var math = ["ALGEBRA", "CALCULUS", "STATISTICS", "EQUATION", "PROBOBILITY", "TRIGANOMITRY", "SOLVE"]
    
    var english = ["ENGLISH", "TEXT", "LITERATURE", "READING", "GRAMMAR", "BOOK", "WRITE", "ESSAY", "PAPER"]
    
    var history = ["HISTORY", "SOCIAL STUDIES", "PEOPLE", "GEOGRAPHY", "DATES", "UNITED STATES", "EUROPE", "BRITISH", "NORTH AMERICA", "SOUTH AMERICA", "AFRICA", "EUROPE", "MIDDLE EAST", "ASIA", "AUSTRALIA", "ANTARTICA", "TIME", "DATES", "CONSTITUTION", "DECLIRATION", "PRESIDENT"]
    
    var science = ["SCIENCE", "BIOLOGY", "BIO", "CHEMISTRY", "CHEM", "PHYSICS", "ENVIROMENTAL", "FORENSICS", "LAB", "EXPIREMENT", "ATOMS", "CARBON", "GLUCOSE", "DESIGN", "ENGINEERING", "BUILD", "MOMENTUM"]
    
    //media
    var media = ["MEDIA", "NETFLIX", "DISNEY PLUS", "HULU", "HBO MAX", "TV", "MOVIES", "BLOCKBUSTER", "OSCARS", "GOLDEN GLOBES", "TONY", "BROADWAY", "SHOW", "ACTING", "SINGING", "SONGS", "MUSIC", "INSTRAMENT", "NOVEL", "BOOK", "READING"]
    
    var netflix = ["NETFLIX", "TV", "MOVIES", "SHOWS","SHOW", "STREAM", "WATCH"]
    
    var reading = ["READING", "BOOK", "FANTASY", "STORY", "SCI-FI", "HISTORICAL FICTION", "NON-FICTION", "NOVEL", "SERIES", "FICTION"]
    
    //about your day
    var time = ["WINTER", "SUMMER", "FALL", "SPRING", "JANUARY", "FEBUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"]
    
    var travel = ["HIKE", "HIKEING", "TRAVEL", "VACTAION", "MOUNTAIN", "DESERT", "BEACH", "GET AWAY"]
    
    var hobbies = ["PIANO", "ART", "GAMING","CHESS", "WOOD WORKING", "BAKING", "COOKING", "WRITING"]
    
    var cat = ["CAT","CATS","KITTEN","KITTY","MEOW", "MEOWS","FELINE","TABBY","PUR","MOUSE","WISKER","MEW"]
    
    var dog = ["DOG","DOGS", "BARK","BARKS","PUPPY","DOGGY","WOLF","CANINE","HOUND","PUP","HOWL","DOGHOUSE","WALK","TREAT"]
    
    
    
    init(){
        
    }
    
    func getArray() -> [[String]] {
        let allWords = [sports, basketball, baseball, volleyball, hockey, football, soccer, swimming, running, school, classes, computerScience, math, english, history, science, media, netflix, reading, time, travel, hobbies, cat, dog]
        return allWords
    }
    
    
}
