//
//  ConversationTopicDataBase.swift
//  AIChatBot
//
//  Created by TEAGAN RETT on 1/10/22.
//

import Foundation

import Foundation
public class ConversationTopicDataBase{
    //sports
    var sports = ["BASKETBALL", "BASEBALL", "VOLLEYBALL", "HOCKEY", "FOOTBALL", "SOCCER", "SWIMMING", "SWIM", "RUNNING", "TRACK", "DEFENSE", "OFFENSE", "WIN", "LOSE"]
    
    var basketball = ["BASKETBALL", "COURT", "ORANGE", "B-BALL", "GUARD", "FORWARD", "SHOOTING", "NET", "SLAM DUNK", "HOOP", "BACKBOARD", "DRIBBLE", "NBA", "WNBA", "BULLS", "LAKERS", "WARRIORS", "NETS", "SUNS", "RAPTORS", "CELTICS", "KNICKS", "HEAT", "MAVERICKS", "BUCKS", "CAVALIERS", "JAZZ", "76ERS", "SPURS", "CLIPPERS", "NUGGETS", "GRIZZLIES", "HORNETS", "WIZARDS", "ROCKETS", "BLAZERS", "KINGS", "TIMBERWOLVES", "PACERS", "HAWKS", "PELICANS", "PISTONS", "CITY THUNDER", "MAGIC", "MYSTICS", "SKY", "ACES", "STORM", "LYNX", "LIBERTY", "MERCURY", "SPARKS", "DREAM", "WINGS", "FEVER", "COMETS", "STARS", "STING", "MONARCHS", "SHOCKS", "ROCKERS", "STARZZ", "SOL", "FIRE", "MIRACLE", "RAGE", "DEFENSE", "OFFENSE", "STEAL", "SHOT", "LAYUP"]
    
    var baseball = ["BASEBALL", "SOFTBALL", "BAT", "FEILD", "DIAMOND", "OUTFEILD", "INFEILD", "MOUND", "BASE", "PITCHER", "FIRSTBASE", "SECONDBASE", "THIRDBASE", "CATCHER", "SHORTSTOP", "RIGHT", "LEFT", "CENTER", "SINGLE", "HOMERUN", "BALL", "STRIKE", "UMPIRE", "MLB", "YANKEES", "BRAVES", "RED SOX", "ASTROS", "DODGERS", "RAYS", "GIANTS", "METS", "ANGELS", "CUBS", "GUARDIANS", "CARDINALS", "MARLINS", "ORIOLES", "ATHLETICS", "PHILLIES", "TIGERS", "WHITE SOX", "TWINS", "REDS", "BLUE JAYS", "RANGERS", "NATIONALS", "ROYALS", "BREWERS", "PIRATES"]
    
    var volleyball = ["VOLLEYBALL", "NET", "SPIKE", "SET", "PASS", "SERVE", "SETTER", "LIBERO", "BLOCKER", "HITTER", "HIT", "DIG", "BLOCK", "DS", "DEFENSE", "OFFENSE"]
    
    var hockey = ["HOCKEY", "PUCK", "ICE", "ICERINK", "RINK", "STICK", "HOCKEY STICK", "NHL", "HURRICANES", "BLUEJACKETS", "DEVILS", "ISLANDERS", "RANGERS", "FLYERS", "PENGUINS", "CAPITALS", "COYOTES", "BLACKHAWKS", "AVALANCHE", "STARS", "WILD", "PREDATORS", "BLUES", "JETS", "BRUINS", "SABERS", "RED WINGS", "PANTHERS", "CANADIENS", "SENATORS", "LIGHTING", "MAPLE LEAFS", "DUCKS", "FLAMES", "OILERS", "KINGS", "SHARKS", "SEATTLE KRAKEN", "CANUCKS", "GOLDEN KNIGHTS"]
    
    var football = ["FOOTBALL", "FEILD", "YARD LINE", "TACKLE", "TOUCHDOWN", "FEILD GOAL", "CENTER", "OFFENSIVE GUARD", "OFFENSIVE TACKLE", "QUARTERBACK", "RUNNING BACK", "WIDE REVEIVER", "TIGHT END", "DEFENSIVE TACKLE", "OFFENSE", "DEFFENSE", "NFL", "BUCCANEERS", "RAIDERS", "PACKERS", "EAGLES", "49ERS", "CHEIFS", "PATRIOTS", "COLTS", "RAVENS", "SAINTS", "RAMS", "VIKINGS", "BRONCOS", "DOLPHINS", "TITANS", "SEAHAWKS", "WASHINGTON FOOTBALL TEAM", "BEARS", "GIANTS", "LIONS", "JAGUARS", "PANTHERS", "JETS", "TEXANS", "COWBOYS", "STEELERS"]
    
    
    var school = ["SCHOOL", "HIGH", "FRESHMAN", "JUNIOR", "SENIOR", "GRADUATE", "TEACHER", "STUDENT", "HOMEWORK", "CLASS", "FRIENDS", "ASSIGNMENT", "ACADEMY", "HALL", "COLLEGE", "COURSE", "CLASSES", "COURSES", "EDUCATION", "GRADES", "TEST", "FINAL", "FINALS", "CAMPUS", "TEACHING", "STUDY"]
    
    var netflix = ["NETFLIX"]
    
    var computerScience = ["COMPUTER SCIENCE", "PROGRAM", "PROGRAMMING", "PROGRAMER", "CODE", "CODING", "JAVA", "SWIFT", "LANGUAGE", "SOFTWARE", "COMPUTER", "SEAVER", "XCODE", "BLUEJ", "JAVASCRIPT", "NETWORK", "LIT", "HACK"]
    
    //about your day
    
    init(){
        
    }
    
}
